name: ci
  
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install qt5-default
    - name: Build
      run: |
        qmake
        make
